<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE empleados [
  <!ELEMENT empleados (empleado+)>
  <!ELEMENT empleado (nombre, apellido, salario)>
  <!-- #PCDATA: puede contener una cadena de caracteres -->
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT apellido (#PCDATA)>
  <!ELEMENT salario (#PCDATA)>
]>
<empleados>
  <empleado>
    <nombre>LUIS</nombre>
    <apellido>SANCHEZ</apellido>
    <salario>30000</salario>
  </empleado>
</empleados>